spring:
  security:
    oauth2:
      client:
        registration:
          auth0:
            client-id: 49t4505xJ7BUKQLH6mzads6ReFr6l2sJ
            client-secret: uzcjtCX4u3kwHp--bHtvvQGO-CAdQYuEkX-Z8qZlX6Xbn3kU2CLRPjClpHeARFbQ
            scope:
              - openid
              - profile
              - email
        provider:
          auth0:
            issuer-uri: https://dev-vttp.jp.auth0.com/