spring:
  security:
    oauth2:
      client:
        registration:
          auth0:
            client-id: KbmXL4jda05CwOA1j8lfnJyd3M0Ovhzj
            client-secret: r2sdUztMxxtBVtYj3dj8QEc0v3PmlCT9DCfCEuOsVpIqcTLLzZPh9jg4K_2nN4yM
            scope:
              - openid
              - profile
              - email
        provider:
          auth0:
            issuer-uri: https://dev-vttp.jp.auth0.com/