spring:
  security:
    oauth2:
      client:
        registration:
          auth0:
            client-id: ${{secrets.CLIENT_ID}}
            client-secret: ${{secrets.CLIENT_SECRET}}
            scope:
              - openid
              - profile
              - email
        provider:
          auth0:
            issuer-uri: https://dev-vttp.jp.auth0.com/
