# This is a basic workflow to help you get started with Actions

name: Compile, test, deploy

# Controls when the workflow will run
on: [ "push" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Export secret variables
      env:
        CLIENT_ID: ${{ secrets.client_id }}
        CLIENT_SECRET: ${{ secrets.client_secret }}
      run: |
        echo $CLIENT_ID $CLIENT_SECRET.
        
    - name: Checkout my repo
      uses: actions/checkout@v3
      
    - name: Setup Java 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Setup Maven
      uses: stCarolas/setup-maven@v4.3
      with:
        maven-version: '3.8.4'
        
    - name: Run test
      run: mvn clean verify
      
    - name: Generate coverage badge
      uses: cicirello/jacoco-badge-generator@v2
      with:
        generate-coverage-badge: true
    - name: Upload coverage badge to DigitalOcean spaces
      uses: BetaHuhn/do-spaces-action@v2
      with:
        access_key: ${{ secrets.access_key }}
        secret_key: ${{ secrets.secret_key }}
        space_name: bigbucket
        space_region: sgp1
        source: .github/badges/jacoco.svg
        out_dir: coverage/${{ github.event.repository.name }}
        permission: public-read
      
    - name: Upload coverage report
      uses: BetaHuhn/do-spaces-action@v2
      with:
        access_key: ${{ secrets.access_key }}
        secret_key: ${{ secrets.secret_key }}
        space_name: bigbucket
        space_region: sgp1
        source: target/site/jacoco
        out_dir: coverage/${{ github.event.repository.name }}/report
